version: '3.3'
services:
    influxdb:
      image: influxdb:latest
      container_name: influxdbV2
      restart: unless-stopped
      environment:
        - DOCKER_INFLUXDB_INIT_MODE=setup
        - DOCKER_INFLUXDB_INIT_USERNAME=my-user
        - DOCKER_INFLUXDB_INIT_PASSWORD=my-password
        - DOCKER_INFLUXDB_INIT_ORG=my-org
        - DOCKER_INFLUXDB_INIT_BUCKET=my-bucket
      ports:
        - '8086:8086'
      volumes:
        - 'influxdb_data:/var/lib/influxdb2'
        - 'influxdb_config:/etc/influxdb2'
